-- Sync shooters table to match Shooter entity

ALTER TABLE shooters ADD COLUMN IF NOT EXISTS is_deaf BOOLEAN DEFAULT false;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS registration_status VARCHAR(30) DEFAULT 'incomplete';
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS pci_id VARCHAR(50);
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS event_type VARCHAR(20);
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS category VARCHAR(50);
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS approved_by BIGINT REFERENCES users(id);
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS guardian_name VARCHAR(255);
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS residential_state VARCHAR(100);
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS pincode VARCHAR(10);
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS signature_url TEXT;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS birth_certificate_url TEXT;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS aadhar_card_url TEXT;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS pan_card_url TEXT;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS passport_doc_url TEXT;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS arms_license_url TEXT;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS affidavit_url TEXT;
ALTER TABLE shooters ADD COLUMN IF NOT EXISTS ipc_card_url TEXT;
